### ISSUE TITLE
CIDR customizing issue in main.template

### ISSUE THREAD

**Issue by jeremypumphrey** [aws-quickstart/quickstart-compliance-nist#3]
While customizing main.template with unique CIDR ranges I ran into a problem in the vpc-production.template section of main.template. That section doesn't have a pProductionCIDR definition so even if you change all the CIDR defs in main.template it will still read in the child default from vpc-production.template and give you an error about invalid CIDR ranges when building the stack. 

The fix is simple, worked for me. Around line 309 add a line defining pProductionCIDR, just like line 367.

Also, why not make all the CIDR entries as inputs so you can change them in the console when creating the stack? Must be a common need to customize the CIDRs.

**Comment by santiagocardenas** [comment]
Hi @jeremypumphrey. Thanks for the feedback.
I think you may be referring to older versions of the template?

It sounds like the best way for this is to make it a map at the top of the template (rather than in each nested stack parameters) or exposing the parameters, so that it can be done on the fly.

@barnesrobert @bmille6 Any further thoughts on this?

**Comment by jeremypumphrey** [comment]
The current main.template file in github, under vpc-production.template around line 309, is missing the following that will fix the problem:
"pProductionCIDR: 10.100.0.0/16"

**Comment by wsupernor** [comment]
Appears to be fixed in current master?
